version: '3.9'
services:
    app:
        build:
            dockerfile: Dockerfile
            context: .
            target: install
            args:
                NODE_ENV: 'development'
        volumes:
            - .:/app/:cached
        command: ['pnpm', 'run', 'dev']
