version: '3.9'
services:
    redis:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        healthcheck:
            test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
            interval: 1s
            timeout: 3s
            retries: 5
    db:
        image: postgres:latest
        volumes:
            - db:/var/lib/postrgresql/data/
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: devlingo
            POSTGRES_DB: devlingo
            POSTGRES_USER: devlingo
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U devlingo']
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 5s
    project-service:
        profiles:
            - all
            - project-service
        depends_on:
            db:
                condition: service_healthy
        build:
            dockerfile: Dockerfile
            context: ./backend
            target: install
            args:
                - TARGET=project-service
        volumes:
            - ./apps/project-service:/app/apps/project-service:cached
            - ./shared:/app/shared:cached
            - ./prisma:/app/prisma:cached
        environment:
            SERVER_PORT: 4000
            DATABASE_URL: postgresql://devlingo:devlingo@db:5432/devlingo
            NODE_ENV: development
        env_file:
            - .env.development
        ports:
            - '4000:4000'
        command: ['pnpm', 'run', 'nest:start-project-service']
    ai-service:
        profiles:
            - all
            - ai-service
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        build:
            dockerfile: Dockerfile
            context: ./backend
            target: install
            args:
                - TARGET=ai-service
        volumes:
            - ./backend/apps/ai-service:/app/apps/ai-service:cached
            - ./backend/shared:/app/shared:cached
            - ./backend/prisma:/app/prisma:cached
        environment:
            SERVER_PORT: 8000
            DATABASE_URL: postgresql://devlingo:devlingo@db:5432/devlingo
            REDIS_CONNECTION_STRING: redis://redis:6379
            NODE_ENV: development
        env_file:
            - .env.development
        ports:
            - '8000:8000'
        command: ['pnpm', 'run', 'nest:start-ai-service']

volumes:
    db:
