version: '3.9'
services:
    redis:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
    db:
        image: postgres:latest
        volumes:
            - db:/var/lib/postrgresql/data/
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: devlingo
            POSTGRES_DB: devlingo
            POSTGRES_USER: devlingo
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U devlingo']
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 5s
    project-service:
        depends_on:
            db:
                condition: service_healthy
        build:
            dockerfile: Dockerfile
            context: .
            target: install
            args:
                - SERVER_PORT=3000
                - TARGET=project-service
        volumes:
            - ./apps/project-service:/app/apps/project-service:cached
            - ./shared:/app/shared:cached
            - ./prisma:/app/prisma:cached
        environment:
            SERVER_PORT: 3000
            DATABASE_URL: postgresql://devlingo:devlingo@db:5432/devlingo
        env_file:
            - .env.development
        ports:
            - '3000:3000'
        command: ['pnpm', 'run', 'nest:start-project-service']
    ai-service:
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        build:
            dockerfile: Dockerfile
            context: .
            target: install
            args:
                - SERVER_PORT=3005
                - TARGET=ai-service
        volumes:
            - ./apps/ai-service:/app/apps/ai-service:cached
            - ./shared:/app/shared:cached
            - ./prisma:/app/prisma:cached
        environment:
            SERVER_PORT: 3005
            DATABASE_URL: postgresql://devlingo:devlingo@db:5432/devlingo
            REDIS_CONNECTION_STRING: redis://redis:6379
        env_file:
            - .env.development
        ports:
            - '3005:3005'
        command: ['pnpm', 'run', 'nest:start-ai-service']

volumes:
    db:
