export enum ApiVersions {
	V1 = '1',
}

export enum TimeUnit {
	OneHourInSeconds = 3600,
	OneSecondInMilliseconds = 1000,
}

export enum Environment {
	Development = 'development',
	Production = 'production',
	Test = 'test',
}

export enum HttpMethod {
	Get = 'GET',
	Post = 'POST',
	Patch = 'PATCH',
	Put = 'PUT',
	Delete = 'DELETE',
}

export enum ServiceType {
	NestJs = 'NestJS',
	NextJs = 'NextJS',
	MongoDB = 'MongoDB',
	Firestore = 'Firestore',
	Cassandra = 'Cassandra',
	DynamoDB = 'DynamoDB',
	Redis = 'Redis',
	Hbase = 'Hbase',
	CosmosDB = 'CosmosDB',
	MySQL = 'MySQL',
	PostgresSQL = 'Postgres',
	SQLServer = 'SQL Server',
	MariaDB = 'MariaDB',
	Firebird = 'Firebird',
	SQLite = 'SQLite',
	Oracle = 'Oracle',
	ExpressJs = 'Express.js',
	KoaJs = 'Koa.js',
	HapiJs = 'Hapi.js',
	Fastify = 'Fastify',
	Litestar = 'Litestar',
	Django = 'Django',
	Flask = 'Flask',
	FastAPI = 'FastAPI',
	Angular = 'Angular',
	React = 'React',
	Solid = 'Solid',
	Svelte = 'Svelte',
	Vue = 'Vue',
	Android = 'Android',
	IOS = 'IOS',
	Flutter = 'Flutter',
	ReactNative = 'ReactNative',
	MailGun = 'Mailgun',
	OpenAi = 'OpenAI',
	SendGrid = 'Sendgrid',
	Stripe = 'Stripe',
	IbmWatson = 'IBM Watson',
	GoogleAi = 'Google AI',
	ClarifaiApi = 'Clarifai API',
	GoogleCloudVisionApi = 'Google Cloud Vision API',
	ConvertKit = 'ConvertKit',
	MailChimp = 'MailChimp',
	FreshSales = 'FreshSales',
	ActiveCampaign = 'ActiveCampaign',
	ConstantContact = 'Constant Contact',
	Adyen = 'Adyen',
	Braintree = 'Braintree',
	Razorpay = 'Razorpay',
	RevenueCat = 'RevenueCat',
	Square = 'Square',
	Paypal = 'PayPal',
	PlayStore = 'PlayStore',
	AppStore = 'AppStore',
	OpenCageGeocoder = 'OpenCage Geocoder',
	BingMaps = 'Bing Maps',
	HereMaps = 'Here Maps',
	Mapbox = 'Mapbox',
	GoogleMaps = 'Google Maps',
	Optimizely = 'Optimizely',
	Segment = 'Segment',
	Tealium = 'Tealium',
	TomTom = 'TomTom',
	HereGeo = 'Here Geo',
	BingGeo = 'Bing Geo',
	MapboxGeo = 'Mapbox Geo',
	GoogleMapsGeo = 'Google Maps Geo',
	OptimizelyAb = 'Optimizely AB',
	VisualWebsiteOptimizer = 'Visual Website Optimizer',
	Unbounce = 'Unbounce',
	AdobeTarget = 'Adobe Target',
	GoogleOptimize = 'Google Optimize',
	Jumio = 'Jumio',
	Veriff = 'Veriff',
	Onfido = 'Onfido',
	Trulioo = 'Trulioo',
	Passbase = 'Passbase',
	Pipedrive = 'Pipedrive',
	ZohoCRM = 'Zoho CRM',
	Hubspot = 'HubSpot',
	Salesforce = 'Salesforce',
	USPS = 'USPS',
	FedEx = 'FedEx',
	DHLAPI = 'DHL API',
	EasyPost = 'EasyPost',
	UPS = 'UPS',
	CoinAPI = 'CoinAPI',
	BlockCypher = 'BlockCypher',
	Nomics = 'Nomics',
	Infura = 'Infura',
	Quicknode = 'QuickNode',
	Alchemy = 'Alchemy',
	CryptoCompare = 'CryptoCompare',
	Coinpaprika = 'Coinpaprika',
	Tierion = 'Tierion',
	CoinGecko = 'CoinGecko',
	Leadiq = 'LeadIQ',
	FullContact = 'FullContact',
	Clearbit = 'Clearbit',
	ZoomInfo = 'ZoomInfo',
	SnovIo = 'Snov.io',
	ZohoDesk = 'Zoho Desk',
	Zendesk = 'Zendesk',
	Intercom = 'Intercom',
	HelpScoutApi = 'Help Scout API',
	Freshdesk = 'Freshdesk',
	Kochava = 'Kochava',
	Singular = 'Singular',
	Adjust = 'Adjust',
	Appsflyer = 'AppsFlyer',
	Branch = 'Branch',
	Vimeo = 'Vimeo',
	Spotify = 'Spotify',
	Deezer = 'Deezer',
	YouTube = 'YouTube',
	SoundCloud = 'SoundCloud',
	OpenWeather = 'OpenWeather',
	AccuWeather = 'AccuWeather',
	Weatherstack = 'Weatherstack',
	GoogleAdwords = 'Google AdWords',
	LinkedInAds = 'LinkedIn Ads',
	TwitterAds = 'Twitter Ads',
	FacebookAds = 'Facebook Ads',
	Plaid = 'Plaid',
	Quodd = 'Quodd',
	Intrinio = 'Intrinio',
	Yodlee = 'Yodlee',
	Finbox = 'Finbox',
	Bandwidth = 'Bandwidth',
	Plivo = 'Plivo',
	Twilio = 'Twilio',
	Vonage = 'Vonage',
	Infobip = 'Infobip',
	Lokalise = 'Lokalise',
	Phrase = 'Phrase',
	DeepLApi = 'DeepL API',
	Smartling = 'Smartling',
	YandexTranslateApi = 'Yandex Translate API',
	GoogleTranslateApi = 'Google Translate API',
	Crowdin = 'Crowdin',
	Transifex = 'Transifex',
	MicrosoftTranslatorTextApi = 'Microsoft Translator Text API',
	GoogleAnalytics = 'Google Analytics',
	Amplitude = 'Amplitude',
	Pendo = 'Pendo',
	Heap = 'Heap',
	Mixpanel = 'Mixpanel',
	Woopra = 'Woopra',
}

export enum SystemComponentType {
	Module = 'Module',
	Controller = 'Controller',
	Endpoint = 'Endpoint',
	Service = 'Service',
}

export enum EdgeType {
	BezierEdge = 'default',
	StraightEdge = 'straight',
	StepEdge = 'step',
	SmoothStepEdg = 'smoothstep',
	SimpleBezier = 'simplebezier',
}

export enum NodeShape {
	ArrowRight = 'arrowRight',
	ArrowLeft = 'arrowLeft',
	Circle = 'circle',
	Database = 'database',
	Diamond = 'diamond',
	Ellipse = 'ellipse',
	Hexagon = 'hexagon',
	ParallelogramRight = 'parallelogramRight',
	ParallelogramLeft = 'parallelogramLeft',
	Rectangle = 'rectangle',
	RoundedRectangle = 'roundedRectangle',
	Triangle = 'triangle',
}
