import { formatDate, sortByDateProp, wait } from '@/utils/time';

describe('time util tests', () => {
	describe('wait tests', () => {
		it('test_wait_with_positive_timeout', async () => {
			const start = Date.now();
			await wait(50);
			const end = Date.now();
			expect(end - start).toBeGreaterThanOrEqual(50);
		});
	});

	// Generated by CodiumAI

	/*
    Code Analysis

    Objective:
    The objective of the formatDate function is to format a given date into a string using the dayjs library.

    Inputs:
    - date: a Date object, a string representing a date, or a number representing a Unix timestamp.
    - format (optional): a string representing the desired format of the output. If not provided, the default format is 'MMMM D, YYYY h:mm A'.

    Flow:
    1. The function takes in a date and an optional format string.
    2. The date is passed to the dayjs library to create a dayjs object.
    3. The dayjs object is then formatted using the provided or default format string.
    4. The formatted date string is returned as the output.

    Outputs:
    - A string representing the formatted date.

    Additional aspects:
    - The function uses the dayjs library for date formatting.
    - The format string follows the syntax of the dayjs library.
    - The function has a default format string if one is not provided.
    - The function can accept different types of input for the date parameter.
    */

	describe('formatDate tests', () => {
		it('formats according to the default formatting', () => {
			expect(formatDate('2022-01-01')).toBe('January 1, 2022 12:00 AM');
		});

		it('formats according to a custom format', () => {
			expect(formatDate('2022-01-01', 'YYYY/MM/DD')).toBe('2022/01/01');
		});
	});

	describe('sortByDateProp tests', () => {
		it('sorts by "createdAt"', () => {
			const collection = [
				{
					createdAt: '2022-01-01T00:00:00.000Z',
					updatedAt: '2022-01-02T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-03T00:00:00.000Z',
					updatedAt: '2022-01-04T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-02T00:00:00.000Z',
					updatedAt: '2022-01-01T00:00:00.000Z',
				},
			];
			const sortedCollection = sortByDateProp(collection)();
			expect(sortedCollection).toEqual([
				{
					createdAt: '2022-01-01T00:00:00.000Z',
					updatedAt: '2022-01-02T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-02T00:00:00.000Z',
					updatedAt: '2022-01-01T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-03T00:00:00.000Z',
					updatedAt: '2022-01-04T00:00:00.000Z',
				},
			]);
		});

		it('sorts by "updatedAt"', () => {
			const collection = [
				{
					createdAt: '2022-01-01T00:00:00.000Z',
					updatedAt: '2022-01-02T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-03T00:00:00.000Z',
					updatedAt: '2022-01-04T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-02T00:00:00.000Z',
					updatedAt: '2022-01-01T00:00:00.000Z',
				},
			];
			const sortedCollection = sortByDateProp(collection)('updatedAt');
			expect(sortedCollection).toEqual([
				{
					createdAt: '2022-01-02T00:00:00.000Z',
					updatedAt: '2022-01-01T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-01T00:00:00.000Z',
					updatedAt: '2022-01-02T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-03T00:00:00.000Z',
					updatedAt: '2022-01-04T00:00:00.000Z',
				},
			]);
		});

		it('sorts ascending', () => {
			const collection = [
				{
					createdAt: '2022-01-01T00:00:00.000Z',
					updatedAt: '2022-01-02T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-03T00:00:00.000Z',
					updatedAt: '2022-01-04T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-02T00:00:00.000Z',
					updatedAt: '2022-01-01T00:00:00.000Z',
				},
			];
			const sortedCollection = sortByDateProp(collection)();
			expect(sortedCollection).toEqual([
				{
					createdAt: '2022-01-01T00:00:00.000Z',
					updatedAt: '2022-01-02T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-02T00:00:00.000Z',
					updatedAt: '2022-01-01T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-03T00:00:00.000Z',
					updatedAt: '2022-01-04T00:00:00.000Z',
				},
			]);
		});

		it('sorts descending', () => {
			const collection = [
				{
					createdAt: '2022-01-01T00:00:00.000Z',
					updatedAt: '2022-01-02T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-03T00:00:00.000Z',
					updatedAt: '2022-01-04T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-02T00:00:00.000Z',
					updatedAt: '2022-01-01T00:00:00.000Z',
				},
			];
			const sortedCollection = sortByDateProp(collection)(
				'createdAt',
				'desc',
			);
			expect(sortedCollection).toEqual([
				{
					createdAt: '2022-01-03T00:00:00.000Z',
					updatedAt: '2022-01-04T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-02T00:00:00.000Z',
					updatedAt: '2022-01-01T00:00:00.000Z',
				},
				{
					createdAt: '2022-01-01T00:00:00.000Z',
					updatedAt: '2022-01-02T00:00:00.000Z',
				},
			]);
		});

		it('handles empty collection', () => {
			const collection: { createdAt: string; updatedAt: string }[] = [];
			const sortedCollection = sortByDateProp(collection)();
			expect(sortedCollection).toEqual([]);
		});
	});
});
